export default {
    PING: 0,
    PONG: 1,

    INIT_USER: 10,

    GAME_START: 20,
    GAME_MESSAGE: 70,

    NOTICE_INVITE: 50,
    NOTICE_JOIN: 51,
    NOTICE_REJECT_INVITE: 52,

    BROADCAST_PUBLIC: 90,
    BROADCAST_ROOM: 91,

    ROOM_CREATE: 80,
    ROOM_EXIT: 81,
    ROOM_APPEND: 82,
}